[package]
name = "gnome-tour"
version = "3.38.0"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
edition = "2018"

[features]
video = ["gst_player", "gst"]

[dependencies]
glib = { version = "0.10", features = ["v2_64"] }
gdk = "0.13"
gtk = { version = "0.9", features= ["v3_16"] }
gio = "0.9"
log = "0.4"
gettext-rs = { version = "0.4", features = ["gettext-system"] }
libhandy = "0.7"
pretty_env_logger = "0.4"
anyhow = "1.0"

[dependencies.gst_player]
version = "0.16"
package = "gstreamer-player"
optional = true

[dependencies.gst]
version = "0.16"
package = "gstreamer"
optional = true

